# Generated by Django 2.1.5 on 2020-06-17 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_homes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bathroom',
            name='code',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bedroom',
            name='code',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parking',
            name='code',
            field=models.IntegerField(default=0),
        ),
    ]
