# Generated by Django 2.1.5 on 2020-06-17 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import dream_homes.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dream_homes', '0002_auto_20200617_0226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy_Ad_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_price', models.FloatField(blank=True, null=True)),
                ('to_price', models.FloatField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=4000)),
                ('address_line', models.CharField(max_length=200)),
                ('bedroom', models.IntegerField(default=1)),
                ('bathroom', models.IntegerField(default=1)),
                ('parking', models.IntegerField(default=1)),
                ('garages', models.IntegerField(default=0)),
                ('land_area', models.CharField(blank=True, max_length=64, null=True)),
                ('contact_name', models.CharField(default='', max_length=64)),
                ('email', models.CharField(default='', max_length=64)),
                ('mobile', models.CharField(default='', max_length=64)),
                ('date_time', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('auction_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Buy_Item_Ad_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Buy_Item_Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('ad_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_inspect_ad_item', to='dream_homes.Buy_Ad_Item')),
            ],
        ),
        migrations.CreateModel(
            name='Buy_Item_Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=dream_homes.models.buy_item_photo_path_)),
                ('ad_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_ad_item', to='dream_homes.Buy_Ad_Item')),
            ],
        ),
        migrations.CreateModel(
            name='Rent_Ad_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_price', models.FloatField()),
                ('title', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=4000)),
                ('address_line', models.CharField(max_length=200)),
                ('bedroom', models.IntegerField(default=1)),
                ('bathroom', models.IntegerField(default=1)),
                ('parking', models.IntegerField(default=1)),
                ('garages', models.IntegerField(default=0)),
                ('contact_name', models.CharField(default='', max_length=64)),
                ('email', models.CharField(default='', max_length=64)),
                ('mobile', models.CharField(default='', max_length=64)),
                ('date_time', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='rent_ad_location', to='dream_homes.Location')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rent_ad_property_type', to='dream_homes.Property_Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_ad_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rent_Item_Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('ad_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_inpect_ad_item', to='dream_homes.Rent_Ad_Item')),
            ],
        ),
        migrations.CreateModel(
            name='Rent_Item_Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=dream_homes.models.rent_item_photo_path_)),
                ('ad_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_ad_item', to='dream_homes.Rent_Ad_Item')),
            ],
        ),
        migrations.AddField(
            model_name='buy_ad_item',
            name='ad_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='buy_item_ad_type', to='dream_homes.Buy_Item_Ad_Type'),
        ),
        migrations.AddField(
            model_name='buy_ad_item',
            name='location',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='buy_ad_location', to='dream_homes.Location'),
        ),
        migrations.AddField(
            model_name='buy_ad_item',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='buy_ad_property_type', to='dream_homes.Property_Type'),
        ),
        migrations.AddField(
            model_name='buy_ad_item',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_ad_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
