# Generated by Django 2.1.5 on 2020-06-18 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dream_homes', '0003_auto_20200617_0550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent_ad_item',
            old_name='bathroom',
            new_name='bathrooms',
        ),
        migrations.RenameField(
            model_name='rent_ad_item',
            old_name='bedroom',
            new_name='bedrooms',
        ),
    ]
