# Generated by Django 2.1.5 on 2020-06-19 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dream_homes', '0006_auto_20200619_0356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy_item_inspection',
            name='ad_item',
        ),
        migrations.RemoveField(
            model_name='rent_item_inspection',
            name='ad_item',
        ),
        migrations.DeleteModel(
            name='Buy_Item_Inspection',
        ),
        migrations.DeleteModel(
            name='Rent_Item_Inspection',
        ),
    ]
