# Generated by Django 2.1.5 on 2020-06-19 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dream_homes', '0007_auto_20200619_0359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy_Item_Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('ad_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_inspect_ad_item', to='dream_homes.Buy_Ad_Item')),
            ],
        ),
        migrations.CreateModel(
            name='Rent_Item_Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('ad_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_inpect_ad_item', to='dream_homes.Rent_Ad_Item')),
            ],
        ),
    ]
