# Generated by Django 2.1.5 on 2020-06-22 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_homes', '0009_auto_20200621_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy_ad_item',
            name='amount_paid',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='buy_ad_item',
            name='payment_pkg',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='rent_ad_item',
            name='amount_paid',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='rent_ad_item',
            name='payment_pkg',
            field=models.CharField(default='', max_length=4),
        ),
    ]
